language: node_js

sudo: false

node_js:
  - "10"
  - "12"
  - "14"

cache:
  directories:
    - node_module

script:
  - npm run build
  - npm run clean
  - npm test

after_success: npm run coverage
